
export const fieldsConfig = {
  tb_id: { label: 'TB ID', type: 'text', faker: 'datatype.uuid' },
  period_id: { label: 'Period ID', type: 'text', faker: 'datatype.uuid' },
  accountable_id: { label: 'Accountable ID', type: 'text', faker: 'datatype.uuid' },

  report_date: { label: 'Report Date', type: 'date', faker: 'date.recent' },
  total_debits: { label: 'Total Debits', type: 'number', faker: 'finance.amount' },
  total_credits: { label: 'Total Credits', type: 'number', faker: 'finance.amount' },

  difference: { label: 'Difference', type: 'number', faker: 'finance.amount' },

  // Mandated
  processing_step: { label: 'Processing Step', type: 'text', faker: 'hacker.verb' },
  unit_price: { label: 'Unit Price', type: 'number', faker: 'finance.amount' },

  // Extras
  is_balanced: { label: 'Is Balanced', type: 'checkbox', faker: 'datatype.boolean' },
  generated_by: { label: 'Generated By', type: 'text', faker: 'name.fullName' },
  notes: { label: 'Notes', type: 'text', faker: 'lorem.sentence' },
  currency: { label: 'Currency', type: 'text', faker: 'finance.currencyCode' }
};

export const entityName = 'Trial Balance';
export const collectionName = 'trial_balance';
