// Auto-generated Default Summary Config
// Generated by scripts/generate_summary_defaults.js

export const defaultAssets = {
    "AccessControls": [
        "Standard"
    ],
    "AfterActionReports": [
        "Standard"
    ],
    "Announcements": [
        "Standard"
    ],
    "ApplicantTracking": [
        "Standard"
    ],
    "ArbitrationRecords": [
        "Standard"
    ],
    "AssetDepreciation": [
        "Standard"
    ],
    "AssetDisposal": [
        "Standard"
    ],
    "AssetLifecycle": [
        "Standard"
    ],
    "AssetTracking": [
        "Standard"
    ],
    "Backorders": [
        "Standard"
    ],
    "BandwidthMonitoring": [
        "Standard"
    ],
    "BankTransfers": [
        "Standard"
    ],
    "Benchmarking": [
        "Standard"
    ],
    "BestPractices": [
        "Standard"
    ],
    "BillableHours": [
        "Standard"
    ],
    "BoardResolutions": [
        "Standard"
    ],
    "BonusesIncentives": [
        "Standard"
    ],
    "BudgetAllocations": [
        "Standard"
    ],
    "BugTracking": [
        "Standard"
    ],
    "BusinessContinuityPlans": [
        "Standard"
    ],
    "BusinessImpactAnalysis": [
        "Standard"
    ],
    "CampaignPerformance": [
        "Standard"
    ],
    "CampaignPlanning": [
        "Standard"
    ],
    "CarbonFootprintTracking": [
        "Standard"
    ],
    "CaseManagement": [
        "Standard"
    ],
    "CashFlowForecasts": [
        "Standard"
    ],
    "CertificationTracking": [
        "Standard"
    ],
    "Certifications": [
        "Standard"
    ],
    "ChangeLogs": [
        "Standard"
    ],
    "ChartOfAccounts": [
        "Standard"
    ],
    "ClaimsManagement": [
        "Standard"
    ],
    "CommunityInvestment": [
        "Standard"
    ],
    "RegulatoryCompliance_ComplianceAudits": [
        "Standard"
    ],
    "CompliancePolicies": [
        "Standard"
    ],
    "ComplianceReporting": [
        "Standard"
    ],
    "ContractCompliance": [
        "Standard"
    ],
    "ContractNegotiations": [
        "Standard"
    ],
    "ContractObligations": [
        "Standard"
    ],
    "ContractRenewalReminders": [
        "Standard"
    ],
    "ContractRenewals": [
        "Standard"
    ],
    "ContractTemplates": [
        "Standard"
    ],
    "ContractTerminations": [
        "Standard"
    ],
    "ContractTypes": [
        "Standard"
    ],
    "ContractualObligations": [
        "Standard"
    ],
    "CorporateSocialResponsibility": [
        "Standard"
    ],
    "CorrectiveActions": [
        "Standard"
    ],
    "CostAnalysis": [
        "Standard"
    ],
    "CourseCatalog": [
        "Standard"
    ],
    "CourtAppearances": [
        "Standard"
    ],
    "CreditManagement": [
        "Standard"
    ],
    "CreditorsLedger": [
        "Standard"
    ],
    "CrisisCommunicationLogs": [
        "Standard"
    ],
    "CrisisResponsePlans": [
        "Standard"
    ],
    "CrisisResponseTeams": [
        "Standard"
    ],
    "CrisisScenarios": [
        "Standard"
    ],
    "CulturalIntegration": [
        "Standard"
    ],
    "CustomerHistory": [
        "Standard"
    ],
    "CustomerInvoices": [
        "Standard"
    ],
    "CustomerSatisfaction": [
        "Standard"
    ],
    "CustomerSegmentation": [
        "Standard"
    ],
    "CustomerSurveys": [
        "Standard"
    ],
    "CustomsDocumentation": [
        "Standard"
    ],
    "DataEncryption": [
        "Standard"
    ],
    "DevelopmentPlans": [
        "Standard"
    ],
    "DisasterRecoveryPlans": [
        "Standard"
    ],
    "DiscountStructures": [
        "Standard"
    ],
    "Discounts": [
        "Standard"
    ],
    "DocumentationManagement": [
        "Standard"
    ],
    "DueDiligence": [
        "Standard"
    ],
    "EmergencyCommunication": [
        "Standard"
    ],
    "EmergencyContacts": [
        "Standard"
    ],
    "EmployeePortals": [
        "Standard"
    ],
    "EmployeeVolunteering": [
        "Standard"
    ],
    "EmployeesList": [
        "Standard"
    ],
    "EmploymentHistory": [
        "Standard"
    ],
    "EnergyAudits": [
        "Standard"
    ],
    "EnergyConsumption": [
        "Standard"
    ],
    "EnergySavingsTracking": [
        "Standard"
    ],
    "EquityInvestments": [
        "Standard"
    ],
    "ExecutiveTraining": [
        "Standard"
    ],
    "FacilityBooking": [
        "Standard"
    ],
    "FacilityMaintenance": [
        "Standard"
    ],
    "FeedbackAnalysis": [
        "Standard"
    ],
    "FirewallConfigurations": [
        "Standard"
    ],
    "FiscalPeriods": [
        "Standard"
    ],
    "FixedIncomeInvestments": [
        "Standard"
    ],
    "Forecasting": [
        "Standard"
    ],
    "ForeignCurrencyAccounts": [
        "Standard"
    ],
    "FreightManagement": [
        "Standard"
    ],
    "GreenInitiatives": [
        "Standard"
    ],
    "HardwareInventory": [
        "Standard"
    ],
    "IdeaSubmission": [
        "Standard"
    ],
    "ImpactReports": [
        "Standard"
    ],
    "IncidentReporting": [
        "Standard"
    ],
    "InnovationPipeline": [
        "Standard"
    ],
    "InspectionRecords": [
        "Standard"
    ],
    "InsurancePolicies": [
        "Standard"
    ],
    "IntegrationPlans": [
        "Standard"
    ],
    "InterestPayments": [
        "Standard"
    ],
    "InternalAudits": [
        "Standard"
    ],
    "InterviewScheduling": [
        "Standard"
    ],
    "InventoryAging": [
        "Standard"
    ],
    "InventoryLocations": [
        "Standard"
    ],
    "InventoryValuation": [
        "Standard"
    ],
    "InvestmentReturns": [
        "Standard"
    ],
    "InvoiceTemplates": [
        "Standard"
    ],
    "IpLicensing": [
        "Standard"
    ],
    "IpLitigation": [
        "Standard"
    ],
    "IpMonitoring": [
        "Standard"
    ],
    "JobDescriptions": [
        "Standard"
    ],
    "JointVentures": [
        "Standard"
    ],
    "JournalEntries": [
        "Standard"
    ],
    "LeadConversionRates": [
        "Standard"
    ],
    "LeadNurturing": [
        "Standard"
    ],
    "LeadScoring": [
        "Standard"
    ],
    "LeadershipWorkshops": [
        "Standard"
    ],
    "LearningPaths": [
        "Standard"
    ],
    "LeaseRenewals": [
        "Standard"
    ],
    "LeaseTerms": [
        "Standard"
    ],
    "LeaveBalances": [
        "Standard"
    ],
    "LegalBriefs": [
        "Standard"
    ],
    "LegalProceedings": [
        "Standard"
    ],
    "LicensingAgreements": [
        "Standard"
    ],
    "LiquidityManagement": [
        "Standard"
    ],
    "LogisticsRoutes": [
        "Standard"
    ],
    "MaintenanceLogs": [
        "Standard"
    ],
    "MarketAnalysis": [
        "Standard"
    ],
    "MediaRelations": [
        "Standard"
    ],
    "MentorshipPrograms": [
        "Standard"
    ],
    "MilestoneCompletion": [
        "Standard"
    ],
    "MilestoneDependencies": [
        "Standard"
    ],
    "MilestoneReporting": [
        "Standard"
    ],
    "NetPromoterScore": [
        "Standard"
    ],
    "NetworkTopology": [
        "Standard"
    ],
    "NewProductDevelopment": [
        "Standard"
    ],
    "Newsletters": [
        "Standard"
    ],
    "NgoPartnerships": [
        "Standard"
    ],
    "NonConformanceReports": [
        "Standard"
    ],
    "ObligationTracking": [
        "Standard"
    ],
    "OfferLetters": [
        "Standard"
    ],
    "OpportunityStages": [
        "Standard"
    ],
    "OrderManagement_OrderFulfillment": [
        "Standard"
    ],
    "OrderStatus": [
        "Standard"
    ],
    "OrderTracking": [
        "Standard"
    ],
    "OvertimeManagement": [
        "Standard"
    ],
    "PartnerAgreements": [
        "Standard"
    ],
    "PartnerCollaboration": [
        "Standard"
    ],
    "PatentFilings": [
        "Standard"
    ],
    "PatentManagement": [
        "Standard"
    ],
    "PaymentTerms": [
        "Standard"
    ],
    "PaymentTracking": [
        "Standard"
    ],
    "Payslips": [
        "Standard"
    ],
    "PenaltiesManagement": [
        "Standard"
    ],
    "PerformanceDashboards": [
        "Standard"
    ],
    "PerformanceReviews_PerformanceMetrics": [
        "Standard"
    ],
    "PickPackShip": [
        "Standard"
    ],
    "PolicyRenewals": [
        "Standard"
    ],
    "PredictiveAnalytics": [
        "Standard"
    ],
    "PressReleases": [
        "Standard"
    ],
    "PreventiveMaintenanceSchedules": [
        "Standard"
    ],
    "OAM_Pricing_PriceLists": [
        "Standard"
    ],
    "ProductCategories": [
        "Standard"
    ],
    "ProductDetails": [
        "Standard"
    ],
    "ProductDiscontinuation": [
        "Standard"
    ],
    "ProductReviews": [
        "Standard"
    ],
    "ProductUpdates": [
        "Standard"
    ],
    "ProjectMilestones": [
        "Standard"
    ],
    "ProjectPhases": [
        "Standard"
    ],
    "ProjectScope": [
        "Standard"
    ],
    "PromotionRecommandations": [
        "Standard"
    ],
    "PromotionalPricing": [
        "Standard"
    ],
    "Promotions": [
        "Standard"
    ],
    "PropertyDetails": [
        "Standard"
    ],
    "PublicStatements": [
        "Standard"
    ],
    "PurchaseOrders": [
        "Standard"
    ],
    "PurchaseRequisitions": [
        "Standard"
    ],
    "QualityStandards": [
        "Standard"
    ],
    "ReconciliationStatements": [
        "Standard"
    ],
    "RecurringInvoices": [
        "Standard"
    ],
    "RegulatoryUpdates": [
        "Standard"
    ],
    "RenewableEnergyInitiatives": [
        "Standard"
    ],
    "RentalAgreements": [
        "Standard"
    ],
    "ReorderPoints": [
        "Standard"
    ],
    "ResearchOutputs": [
        "Standard"
    ],
    "ResearchProposals": [
        "Standard"
    ],
    "ResolutionTimeTracking": [
        "Standard"
    ],
    "ResourceAllocation": [
        "Standard"
    ],
    "RevenueSharingAgreements": [
        "Standard"
    ],
    "ReviewSchedules": [
        "Standard"
    ],
    "RiskAssessments": [
        "Standard"
    ],
    "RiskIdentification": [
        "Standard"
    ],
    "RiskMitigationPlans": [
        "Standard"
    ],
    "RiskResponsePlanning": [
        "Standard"
    ],
    "RiskScoring": [
        "Standard"
    ],
    "RoiAnalysis": [
        "Standard"
    ],
    "SafetyTraining": [
        "Standard"
    ],
    "SalaryStructure": [
        "Standard"
    ],
    "SalesForecasting": [
        "Standard"
    ],
    "SecurityAudits": [
        "Standard"
    ],
    "ServiceContracts_ServiceLevelAgreements": [
        "Standard"
    ],
    "SettlementAgreements": [
        "Standard"
    ],
    "ShiftSchedules": [
        "Standard"
    ],
    "ShipmentTracking": [
        "Standard"
    ],
    "SkillAssessments": [
        "Standard"
    ],
    "SoftwareDevelopmentLifecycle": [
        "Standard"
    ],
    "SoftwareLicenses": [
        "Standard"
    ],
    "Sops": [
        "Standard"
    ],
    "StakeholderAnalysis": [
        "Standard"
    ],
    "StakeholderCommunication": [
        "Standard"
    ],
    "StakeholderFeedback": [
        "Standard"
    ],
    "StockLevels": [
        "Standard"
    ],
    "StrategicGoals": [
        "Standard"
    ],
    "SupplierBids": [
        "Standard"
    ],
    "SupplierPerformance": [
        "Standard"
    ],
    "SupplierPerformanceEvaluation": [
        "Standard"
    ],
    "SupportEntitlements": [
        "Standard"
    ],
    "SustainableSourcing": [
        "Standard"
    ],
    "SwotAnalysis": [
        "Standard"
    ],
    "SynergyTracking": [
        "Standard"
    ],
    "SystemsIntegration": [
        "Standard"
    ],
    "TargetIdentification": [
        "Standard"
    ],
    "TaskAssignments": [
        "Standard"
    ],
    "TaskDeadlines": [
        "Standard"
    ],
    "TaskDependencies": [
        "Standard"
    ],
    "TenantRecords": [
        "Standard"
    ],
    "TicketEscalation": [
        "Standard"
    ],
    "TicketPrioritization": [
        "Standard"
    ],
    "TicketResolution": [
        "Standard"
    ],
    "TimeTracking": [
        "Standard"
    ],
    "Attendance_TimesheetApprovals": [
        "Standard"
    ],
    "TrainingNeedsAnalysis": [
        "Standard"
    ],
    "TrainingPrograms": [
        "Standard"
    ],
    "TrainingRecords": [
        "Standard"
    ],
    "TreasuryPolicies": [
        "Standard"
    ],
    "TrialBalance": [
        "Standard"
    ],
    "UserActivityTracking": [
        "Standard"
    ],
    "UtilityManagement": [
        "Standard"
    ],
    "VarianceAnalysis": [
        "Standard"
    ],
    "VatGstRecords": [
        "Standard"
    ],
    "VendorAssessments": [
        "Standard"
    ],
    "VendorOnboarding": [
        "Standard"
    ],
    "VendorScorecards": [
        "Standard"
    ],
    "VendorsList": [
        "Standard"
    ],
    "VersionControl": [
        "Standard"
    ],
    "VolunteerInitiatives": [
        "Standard"
    ],
    "WarehouseLayouts": [
        "Standard"
    ],
    "WarrantyManagement": [
        "Standard"
    ],
    "WasteManagement": [
        "Standard"
    ],
    "WinLossAnalysis": [
        "Standard"
    ],
    "WorkOrders": [
        "Standard"
    ],
    "entity_comments_history": [
        "Standard"
    ],
    "entity_workflow_rules": [
        "Standard"
    ],
    "manager_action_logs": [
        "Standard"
    ]
};

export const defaultLiabilities = {
    "DebtMaturitySchedules": [
        "Standard"
    ],
    "DebtorAging": [
        "Standard"
    ],
    "LoanAgreements": [
        "Standard"
    ],
    "PropertyTaxes": [
        "Standard"
    ],
    "TaxAudits": [
        "Standard"
    ],
    "TaxCredits": [
        "Standard"
    ],
    "TaxFilings": [
        "Standard"
    ],
    "VendorInvoices": [
        "Standard"
    ],
    "WithholdingTaxes": [
        "Standard"
    ]
};
