const fs = require('fs');
const path = require('path');
const glob = require('glob');

const SRC_DIR = path.resolve(__dirname, '../src/components/Management');
const OUTPUT_FILE = path.resolve(__dirname, '../src/pages/defaultSummaryConfig.js');

console.log('Generating defaultSummaryConfig.js...');

function generateDefaults() {
    // Read configRegistry.js to get the actual keys used in the system
    const registryPath = path.resolve(SRC_DIR, 'configRegistry.js');
    if (!fs.existsSync(registryPath)) {
        console.error("configRegistry.js not found!");
        return;
    }

    const registryContent = fs.readFileSync(registryPath, 'utf8');

    // Extract exported keys: "export { ... }" block or "export const key = ..."
    // The registry usually does named exports like: "export { AccessControls, ... };" or "export const AccessControls = ..."
    // Let's assume the standard patterns.
    // Pattern 1: export { Key, Key2 }
    // Pattern 2: export * as Key from ...

    // Based on previous views, it ends with:
    // export {
    //    Key1,
    //    Key2,
    //    ...
    // };

    // Pattern: const configRegistry = { ... };
    const configBlockMatch = registryContent.match(/const\s+configRegistry\s*=\s*{([\s\S]*?)};/);
    let keys = [];

    if (configBlockMatch) {
        const block = configBlockMatch[1];
        // Split by comma, clean whitespace
        keys = block.split(',')
            .map(k => k.trim())
            .filter(k => k && !k.startsWith('//'));

        // Extract Key from "'Key': Value"
        keys = keys.map(k => {
            const parts = k.split(':');
            if (parts.length < 2) return null; // Filter out malformed lines
            let key = parts[0].trim();
            // Clean comments
            key = key.split('//')[0].trim();
            key = key.replace(/['"]/g, ''); // Remove quotes
            return key;
        }).filter(k => k);
    }

    if (keys.length === 0) {
        // Fallback: try export { ... } pattern just in case
        const exportBlockMatch = registryContent.match(/export\s*{([\s\S]*?)};/);
        // ... existing fallback logic ...
        if (exportBlockMatch) {
            keys = exportBlockMatch[1].split(',')
                .map(k => k.split(':')[0].trim()) // handle alias or key:val
                .map(k => k.split('//')[0].trim()) // comments
                .map(k => k.replace(/['"]/g, '')) // quotes
                .filter(k => k);
        }
    }

    if (keys.length === 0) {
        console.error("Could not find any exported keys in configRegistry.js");
        return;
    }

    const assets = {};
    const liabilities = {};

    keys.forEach(key => {
        // Classification Heuristics based on Key Name
        const lowerKey = key.toLowerCase();
        let isLiability = false;

        if (lowerKey.includes('payable') ||
            lowerKey.includes('debt') ||
            lowerKey.includes('tax') ||
            lowerKey.includes('payroll') ||
            lowerKey.includes('expense') ||
            lowerKey.includes('liability') ||
            lowerKey.includes('loan') ||
            (lowerKey.includes('invoice') && lowerKey.includes('vendor'))) {
            isLiability = true;
        }

        // Force some known categories
        if (lowerKey.includes('receivable')) isLiability = false;
        if (lowerKey.includes('bank')) isLiability = false;
        if (lowerKey.includes('asset')) isLiability = false;
        if (lowerKey.includes('inventory')) isLiability = false;
        if (lowerKey.includes('investment')) isLiability = false;
        if (lowerKey.includes('sales')) isLiability = false;

        if (isLiability) {
            liabilities[key] = ["Standard"];
        } else {
            assets[key] = ["Standard"];
        }
    });

    const fileContent = `// Auto-generated Default Summary Config
// Generated by scripts/generate_summary_defaults.js

export const defaultAssets = ${JSON.stringify(assets, null, 4)};

export const defaultLiabilities = ${JSON.stringify(liabilities, null, 4)};
`;

    fs.writeFileSync(OUTPUT_FILE, fileContent);
    console.log(`Generated defaults for ${Object.keys(assets).length} assets and ${Object.keys(liabilities).length} liabilities using keys from configRegistry.`);
}

generateDefaults();
